version: "3.8"

services:
  accounts-api-app:
    container_name: accounts-api-app-cloud
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV}
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DYNAMODB_ENDPOINT=${DYNAMODB_ENDPOINT}